export const registry = [
  // nav
  { key: 'nav.home',     defaultValue: 'בית',       section: 'nav', label: 'קישור: בית',         description: 'פריט בתפריט העליון של האתר', multiline: false, previewType: 'nav-link', previewPath: '/#navbar' },
  { key: 'nav.about',    defaultValue: 'אודות',      section: 'nav', label: 'קישור: אודות',        description: 'פריט בתפריט העליון של האתר', multiline: false, previewType: 'nav-link', previewPath: '/#navbar' },
  { key: 'nav.services', defaultValue: 'שירותים',    section: 'nav', label: 'קישור: שירותים',      description: 'פריט בתפריט העליון של האתר', multiline: false, previewType: 'nav-link', previewPath: '/#navbar' },
  { key: 'nav.projects', defaultValue: 'פרויקטים',   section: 'nav', label: 'קישור: פרויקטים',     description: 'פריט בתפריט העליון של האתר', multiline: false, previewType: 'nav-link', previewPath: '/#navbar' },
  { key: 'nav.contact',  defaultValue: 'צור קשר',    section: 'nav', label: 'קישור: צור קשר',      description: 'פריט בתפריט העליון של האתר', multiline: false, previewType: 'nav-link', previewPath: '/#navbar' },

  // footer
  { key: 'footer.tagline',       defaultValue: 'נגרות וחיפויים בגובה העיניים',  section: 'footer', label: 'סלוגן הפוטר',            description: 'המשפט הקצר שמופיע בפוטר מתחת לשם החברה',           multiline: false, previewType: 'paragraph', previewPath: '/#footer' },
  { key: 'footer.quickLinks',    defaultValue: 'ניווט',                         section: 'footer', label: 'כותרת: ניווט',            description: 'כותרת העמודה של קישורי הניווט בפוטר',              multiline: false, previewType: 'heading',   previewPath: '/#footer' },
  { key: 'footer.contact',       defaultValue: 'יצירת קשר',                     section: 'footer', label: 'כותרת: יצירת קשר',        description: 'כותרת העמודה של פרטי הקשר בפוטר',                  multiline: false, previewType: 'heading',   previewPath: '/#footer' },
  { key: 'footer.rights',        defaultValue: 'כל הזכויות שמורות',             section: 'footer', label: 'טקסט זכויות יוצרים',      description: 'מופיע בתחתית הפוטר ליד שנת הזכויות',               multiline: false, previewType: 'mono',      previewPath: '/#footer' },
  { key: 'footer.terms',         defaultValue: 'תנאי שימוש',                    section: 'footer', label: 'קישור: תנאי שימוש',        description: 'קישור בתחתית הפוטר',                               multiline: false, previewType: 'nav-link',  previewPath: '/#footer' },
  { key: 'footer.privacy',       defaultValue: 'פרטיות',                        section: 'footer', label: 'קישור: פרטיות',            description: 'קישור בתחתית הפוטר',                               multiline: false, previewType: 'nav-link',  previewPath: '/#footer' },
  { key: 'footer.accessibility', defaultValue: 'נגישות',                        section: 'footer', label: 'קישור: נגישות',            description: 'קישור בתחתית הפוטר',                               multiline: false, previewType: 'nav-link',  previewPath: '/#footer' },

  // home hero
  { key: 'home.hero.eyebrow',       defaultValue: 'Y.SCH. Engineers · גבעת אלה',                                                                                                                                                                    section: 'home', label: 'כותרת קטנה מעל הכותרת הראשית',       description: 'מופיעה בראש דף הבית, מעל הכותרת הגדולה',                                                   multiline: false, previewType: 'eyebrow',        previewPath: '/#hero' },
  { key: 'home.hero.title.1',       defaultValue: 'נגרות',                                                                                                                                                                                           section: 'home', label: 'כותרת ראשית: שורה 1',                 description: 'השורה הראשונה של הכותרת הגדולה במרכז דף הבית',                                             multiline: false, previewType: 'display-title',  previewPath: '/#hero' },
  { key: 'home.hero.title.2',       defaultValue: 'וחיפויים.',                                                                                                                                                                                        section: 'home', label: 'כותרת ראשית: שורה 2',                 description: 'השורה השנייה של הכותרת הגדולה',                                                            multiline: false, previewType: 'display-title',  previewPath: '/#hero' },
  { key: 'home.hero.title.3',       defaultValue: 'בגובה העיניים.',                                                                                                                                                                                   section: 'home', label: 'כותרת ראשית: שורה 3 (מודגש)',         description: 'השורה השלישית של הכותרת — מופיעה באלכסון להדגשה',                                          multiline: false, previewType: 'display-title',  previewPath: '/#hero' },
  { key: 'home.hero.lead',          defaultValue: 'מעל שני עשורים של ייצור נגרות ברמה אדריכלית – חזיתות HPL, חיפויי לובי ונגרות פנים מוקפדת, לפרויקטים פרטיים, מסחריים וציבוריים בכל רחבי הארץ.', section: 'home', label: 'פסקת תיאור ראשית',                    description: 'הפסקה הארוכה שמתארת את החברה, מופיעה מתחת לכותרת בדף הבית',                               multiline: true,  previewType: 'paragraph',     previewPath: '/#hero' },
  { key: 'home.hero.servicesLabel', defaultValue: 'השירותים שלנו',                                                                                                                                                                                    section: 'home', label: 'תווית: השירותים שלנו',                description: 'כותרת קטנה מעל רשימת השירותים בדף הבית',                                                   multiline: false, previewType: 'mono',           previewPath: '/#hero' },
  { key: 'home.hero.servicesValue', defaultValue: 'חיפוי HPL · נגרות · לובי',                                                                                                                                                                        section: 'home', label: 'סיכום שירותים',                       description: 'שורה אחת המסכמת את עיקרי השירותים',                                                       multiline: false, previewType: 'plain',          previewPath: '/#hero' },
  { key: 'home.hero.servicesNote',  defaultValue: 'תכנון · ייצור · התקנה',                                                                                                                                                                            section: 'home', label: 'הערת שירותים',                        description: 'הערה קצרה מתחת לסיכום השירותים',                                                           multiline: false, previewType: 'plain',          previewPath: '/#hero' },
  { key: 'home.hero.ctaLabel',      defaultValue: 'לפרויקט חדש',                                                                                                                                                                                      section: 'home', label: 'תווית: קריאה לפעולה',                description: 'טקסט קטן מעל הכפתורים בדף הבית',                                                          multiline: false, previewType: 'mono',           previewPath: '/#hero' },
  { key: 'home.hero.ctaPrimary',    defaultValue: 'לקבלת הצעת מחיר ←',                                                                                                                                                                               section: 'home', label: 'כפתור ראשי: צור קשר',                description: 'הכפתור השחור הגדול בדף הבית — בלחיצה עוברים לעמוד צור קשר',                               multiline: false, previewType: 'button-primary', previewPath: '/#hero' },
  { key: 'home.hero.ctaGhost',      defaultValue: 'תיק עבודות',                                                                                                                                                                                       section: 'home', label: 'כפתור משני: תיק עבודות',             description: 'הכפתור הקטן יותר ליד הכפתור הראשי, מוביל לעמוד הפרויקטים',                               multiline: false, previewType: 'button-ghost',  previewPath: '/#hero' },
];

export function registryToMap() {
  return Object.fromEntries(registry.map(({ key, defaultValue }) => [key, defaultValue]));
}
